In [1]:
import torch
print(torch.__version__)  # Display PyTorch version
print(torch.cuda.is_available())  # Check if CUDA is available
print(torch.cuda.get_device_name(0))  # Get the name of your GPU

2.1.0+cu121
True
NVIDIA GeForce RTX 3050 6GB Laptop GPU


In [2]:
# Проверим доступное устройство
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Текущий девайс:", device)

# Создаем тензоры
a = torch.rand(10000, 10000, device=device)
b = torch.rand(10000, 10000, device=device)

# Вычисления на GPU
c = torch.matmul(a, b)

print("Матрица успешно умножена на:", device)
print("Shape результата:", c.shape)

Текущий девайс: cuda
Матрица успешно умножена на: cuda
Shape результата: torch.Size([10000, 10000])


In [ ]:
# Скачиваем USPTO-15k
!wget https://github.com/wengong-jin/nips17-rexgen/raw/refs/heads/master/USPTO-15K/data.zip

In [4]:
# распаковываем 
!unzip data.zip 

Archive:  data.zip
   creating: data/
  inflating: data/connor_original.tsv  
  inflating: data/test.txt           
  inflating: data/train.txt          
  inflating: data/valid.txt          


In [3]:
# клонируем скрипты с гитхаба
!git clone https://github.com/maryamastero/Atom-matching-network.git
!cd Atom-matching-network
# поменяли название на Atom_matching_network

Cloning into 'Atom-matching-network'...
remote: Enumerating objects: 407, done.
remote: Counting objects: 100% (83/83), done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 407 (delta 40), reused 11 (delta 11), pack-reused 324 (from 1)
Receiving objects: 100% (407/407), 11.04 MiB | 7.11 MiB/s, done.
Resolving deltas: 100% (191/191), done.


In [ ]:
# preprocessing
!python Atom_matching_network/dataset/preprocessing.py 
# поменяли в скрипте ссылки на файлы с данными

In [3]:
# creating molgraphdataset
!python Atom_matching_network/dataset/molgraphdataset.py
# поменяли в скрипте ссылки на файлы с данными

/home/alpiano/miniconda3/envs/chem_env/lib/python3.10/site-packages/torch_geometric/deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])
48
tensor([28, 45, 35,  9, 11, 38, 40, 46, 41,  5,  3, 14,  8, 32, 42, 43, 30, 44,
        18, 29, 24,  4, 25,  1,  2, 23, 13, 36, 16,  0,  6, 19, 21, 15, 39, 10,
        22, 37, 33,  7, 47, 17, 31, 12, 27, 34, 20, 26])


In [5]:
# реализация amnet
!python Atom_matching_network/AMNet/amnet.py
# корректировка device в скрипте

tensor([[0.9535, 0.0184, 0.0216, 0.0065],
        [0.0222, 0.9413, 0.0131, 0.0234],
        [0.0194, 0.0097, 0.9358, 0.0351],
        [0.0378, 0.1132, 0.2281, 0.6209]], grad_fn=<IndexBackward0>)
True
tensor(0.3466, device='cuda:0')


In [6]:
# wl (Тест Вайсфейлера-Лемана)
!python Atom_matching_network/utils/wl.py

In [60]:
# amnet_train
!python Atom_matching_network/train/amnet_train.py
# исправили проблему импорта модулей, добавили подробный логгер в скрипт

Device: cuda
GPU: NVIDIA GeForce RTX 3050 6GB Laptop GPU
Memory allocated: 0.00 GB
/home/alpiano/miniconda3/envs/chem_env/lib/python3.10/site-packages/torch_geometric/deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
FMNet(
gnn=GIN(111, 512, num_layers=3, batch_norm=False, cat=True, lin=True),

Namespace(num_wl_iterations=3, node_features_dim=111, edge_feature_dim=10, santitize=False, embedding_dim=512, num_layers=3, lr=0.0001, n_epochs=200, batch_size=1)
  0%|                                                   | 0/200 [00:00<?, ?it/s]Epoch: 01 *****
Train Loss: 0.5147 | Train Acc: 74.72%
  0%|▏                                      | 1/200 [05:03<16:47:14, 303.69s/it]Epoch: 02 *****
Train Loss: 0.3985 | Train Acc: 77.86%
  1%|▍                                      | 2/200 [10:14<16:56:39, 308.08s/it]Epoch: 03 *****
Train Loss: 0.3704 | Train Acc: 78.73%
  2%|▌                                      | 3/200 [15:23<16:53:07

In [22]:
!python Atom_matching_network/Test/test_one_mol.py
# корректировка device, исправили проблему импорта модулей в скрипте

--------------------
/home/alpiano/miniconda3/envs/chem_env/lib/python3.10/site-packages/torch_geometric/deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
cuda
FMNet(
gnn=GIN(111, 512, num_layers=3, batch_norm=False, cat=True, lin=True),

Namespace(num_wl_iterations=3, node_features_dim=111, edge_feature_dim=None, santitize=False, embedding_dim=512, num_layers=3, lr=0.001, batch_size=1)
[{0, 9}, {1}, {2}, {3}, {4}, {5}, {6}, {7}, {8}, {10, 12}, {11}, {13}, {14}, {15}, {16}, {17}, {18}]
********************
acc: 0.6842105263157895
h1: 0.5789473684210527
h3: 1.0
h5: 1.0
h10: 1.0
0.9010107670441664
gt, atom mapping tensor([17, 11, 13, 18,  2,  4,  7, 15, 16,  3, 10, 12,  8,  1,  0,  5,  9,  6,
        14], device='cuda:0')
pred, atom mapping [15, 7, 13, 4, 13, 4, 7, 15, 1, 3, 12, 10, 3, 1, 9, 5, 0, 6, 14]


In [24]:
# тест другой молекулы
!python Atom_matching_network/Test/test_one_mol.py
# корректировка device, исправили проблему импорта модулей в скрипте

--------------------
/home/alpiano/miniconda3/envs/chem_env/lib/python3.10/site-packages/torch_geometric/deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
cuda
FMNet(
gnn=GIN(111, 512, num_layers=3, batch_norm=False, cat=True, lin=True),

Namespace(num_wl_iterations=3, node_features_dim=111, edge_feature_dim=None, santitize=False, embedding_dim=512, num_layers=3, lr=0.001, batch_size=1)
[{0}, {1}, {2}, {3}, {4}, {5}, {10, 6}, {7}, {8}, {9}, {11}, {12}, {13}, {14}, {15}]
********************
acc: 0.625
h1: 0.5625
h3: 1.0
h5: 1.0
h10: 1.0
0.8333826059048329
gt, atom mapping tensor([14,  8,  9, 15, 12,  2,  3,  0,  7,  1,  5, 13,  6, 10,  4, 11],
       device='cuda:0')
pred, atom mapping [14, 8, 8, 14, 12, 2, 7, 0, 7, 2, 11, 4, 10, 6, 4, 11]


In [26]:
# тест другой молекулы
!python Atom_matching_network/Test/test_one_mol.py
# корректировка device, исправили проблему импорта модулей в скрипте

--------------------
/home/alpiano/miniconda3/envs/chem_env/lib/python3.10/site-packages/torch_geometric/deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
cuda
FMNet(
gnn=GIN(111, 512, num_layers=3, batch_norm=False, cat=True, lin=True),

Namespace(num_wl_iterations=3, node_features_dim=111, edge_feature_dim=None, santitize=False, embedding_dim=512, num_layers=3, lr=0.001, batch_size=1)
[{0, 11}, {1}, {2}, {3}, {4, 13}, {5}, {6}, {7}, {8}, {9, 18, 28}, {10}, {12}, {14}, {15}, {16, 25}, {17}, {19}, {20}, {21}, {22}, {23}, {24}, {26}, {33, 27}, {29}, {30}, {31}, {32}, {34}]
********************
acc: 1.0
h1: 0.8571428571428571
h3: 1.0
h5: 1.0
h10: 1.0
0.9326219740492461
gt, atom mapping tensor([19, 33, 23, 27, 29,  2, 17, 34, 14,  0, 11, 12,  1, 21, 10, 31,  7, 32,
        22, 15,  3, 26,  5, 28,  9, 18,  8, 13, 25,  6, 16,  4, 24, 20, 30],
       device='cuda:0')
pred, atom mapping [19, 27, 23, 27, 29, 2, 17, 34, 14, 11,

In [27]:
# тест целого батча
!python Atom_matching_network/Test/test_batch.py

--------------------
/home/alpiano/miniconda3/envs/chem_env/lib/python3.10/site-packages/torch_geometric/deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
cuda
FMNet(
gnn=GIN(111, 512, num_layers=3, batch_norm=False, cat=True, lin=True),

Namespace(num_wl_iterations=3, node_features_dim=111, edge_feature_dim=10, santitize=False, embedding_dim=512, num_layers=3, lr=0.001, batch_size=1)
********************
Средняя точность модели: 0.9687 (96.87%)
Медианная точность: 1.0000
Стандартное отклонение: 0.0531
Минимальная точность: 0.6250
Максимальная точность: 1.0000


## МОЙ ПРОЕКТ ##

In [ ]:
!wget https://github.com/wengong-jin/nips17-rexgen/raw/refs/heads/master/USPTO-15K/data.zip

In [4]:
!unzip data.zip 

Archive:  data.zip
   creating: data/
  inflating: data/connor_original.tsv  
  inflating: data/test.txt           
  inflating: data/train.txt          
  inflating: data/valid.txt          


In [3]:
!git clone https://github.com/maryamastero/Atom-matching-network.git
!cd Atom-matching-network

Cloning into 'Atom-matching-network'...
remote: Enumerating objects: 407, done.
remote: Counting objects: 100% (83/83), done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 407 (delta 40), reused 11 (delta 11), pack-reused 324 (from 1)
Receiving objects: 100% (407/407), 11.04 MiB | 7.11 MiB/s, done.
Resolving deltas: 100% (191/191), done.


In [ ]:
# preprocessing
!python Atom_matching_network/dataset/preprocessing.py 

In [3]:
# creating molgraphdataset
!python Atom_matching_network/dataset/molgraphdataset.py

/home/alpiano/miniconda3/envs/chem_env/lib/python3.10/site-packages/torch_geometric/deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])
48
tensor([28, 45, 35,  9, 11, 38, 40, 46, 41,  5,  3, 14,  8, 32, 42, 43, 30, 44,
        18, 29, 24,  4, 25,  1,  2, 23, 13, 36, 16,  0,  6, 19, 21, 15, 39, 10,
        22, 37, 33,  7, 47, 17, 31, 12, 27, 34, 20, 26])


In [37]:
import pandas as pd
from sklearn.model_selection import KFold
import os

# Путь к файлам
data_dir = "SanitizeMol_data"
folds_dir = os.path.join(data_dir, "folds")
os.makedirs(folds_dir, exist_ok=True)

# Загружаем данные с двумя колонками
train_df = pd.read_csv(os.path.join(data_dir, "train.csv"), sep=",", header=None)
valid_df = pd.read_csv(os.path.join(data_dir, "valid.csv"), sep=",", header=None)

# Объединяем train и valid для фолдов
full_df = pd.concat([train_df, valid_df], ignore_index=True)

# Кол-во фолдов
k = 5
kf = KFold(n_splits=k, shuffle=True, random_state=42)

# Разбиваем и сохраняем фолды
for fold, (train_idx, val_idx) in enumerate(kf.split(full_df)):
    train_fold = full_df.iloc[train_idx]
    val_fold = full_df.iloc[val_idx]

    train_path = os.path.join(folds_dir, f"train_fold{fold}.csv")
    val_path   = os.path.join(folds_dir, f"val_fold{fold}.csv")

    train_fold.to_csv(train_path, sep=",", header=False, index=False)
    val_fold.to_csv(val_path,   sep=",", header=False, index=False)

    print(f"✅ Fold {fold}: saved {len(train_fold)} train / {len(val_fold)} val")

✅ Fold 0: saved 5973 train / 1494 val
✅ Fold 1: saved 5973 train / 1494 val
✅ Fold 2: saved 5974 train / 1493 val
✅ Fold 3: saved 5974 train / 1493 val
✅ Fold 4: saved 5974 train / 1493 val


In [17]:
# реализация amnet
!python Atom_matching_network/AMNet/amnet.py

tensor([[0.9535, 0.0184, 0.0216, 0.0065],
        [0.0222, 0.9413, 0.0131, 0.0234],
        [0.0194, 0.0097, 0.9358, 0.0351],
        [0.0378, 0.1132, 0.2281, 0.6209]], grad_fn=<IndexBackward0>)
True
tensor(0.3466, device='cuda:0')


In [18]:
# wl (Тест Вайсфейлера-Лемана)
!python Atom_matching_network/utils/wl.py

In [1]:
# amnet_train
!python Atom_matching_network/train/amnet_train_fold.py --fold 0

Device: cuda
GPU: NVIDIA GeForce RTX 3050 6GB Laptop GPU
Memory allocated: 0.00 GB
/home/alpiano/miniconda3/envs/chem_env/lib/python3.10/site-packages/torch_geometric/deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
FMNet(
gnn=GIN(111, 512, num_layers=3, batch_norm=False, cat=True, lin=True),

Namespace(num_wl_iterations=3, node_features_dim=111, edge_feature_dim=10, santitize=False, embedding_dim=512, num_layers=3, lr=0.0001, n_epochs=80, batch_size=1, fold=0)
  0%|                                                    | 0/80 [00:00<?, ?it/s]Epoch: 01 *****
Train Loss: 0.5327 | Train Acc: 74.19%
  1%|▌                                        | 1/80 [02:57<3:53:10, 177.09s/it]Epoch: 02 *****
Train Loss: 0.4029 | Train Acc: 77.74%
  2%|█                                        | 2/80 [05:50<3:47:23, 174.92s/it]Epoch: 03 *****
Train Loss: 0.3762 | Train Acc: 78.52%
  4%|█▌                                       | 3/80 [08:44<

In [2]:
# amnet_train
!python Atom_matching_network/train/amnet_train_fold.py --fold 1

Device: cuda
GPU: NVIDIA GeForce RTX 3050 6GB Laptop GPU
Memory allocated: 0.00 GB
/home/alpiano/miniconda3/envs/chem_env/lib/python3.10/site-packages/torch_geometric/deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
FMNet(
gnn=GIN(111, 512, num_layers=3, batch_norm=False, cat=True, lin=True),

Namespace(num_wl_iterations=3, node_features_dim=111, edge_feature_dim=10, santitize=False, embedding_dim=512, num_layers=3, lr=0.0001, n_epochs=80, batch_size=1, fold=1)
  0%|                                                    | 0/80 [00:00<?, ?it/s]Epoch: 01 *****
Train Loss: 0.5327 | Train Acc: 74.26%
  1%|▌                                        | 1/80 [02:58<3:54:39, 178.22s/it]Epoch: 02 *****
Train Loss: 0.4040 | Train Acc: 77.73%
  2%|█                                        | 2/80 [05:55<3:50:39, 177.43s/it]Epoch: 03 *****
Train Loss: 0.3759 | Train Acc: 78.59%
  4%|█▌                                       | 3/80 [08:51<

In [3]:
# amnet_train
!python Atom_matching_network/train/amnet_train_fold.py --fold 2

Device: cuda
GPU: NVIDIA GeForce RTX 3050 6GB Laptop GPU
Memory allocated: 0.00 GB
/home/alpiano/miniconda3/envs/chem_env/lib/python3.10/site-packages/torch_geometric/deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
FMNet(
gnn=GIN(111, 512, num_layers=3, batch_norm=False, cat=True, lin=True),

Namespace(num_wl_iterations=3, node_features_dim=111, edge_feature_dim=10, santitize=False, embedding_dim=512, num_layers=3, lr=0.0001, n_epochs=80, batch_size=1, fold=2)
  0%|                                                    | 0/80 [00:00<?, ?it/s]Epoch: 01 *****
Train Loss: 0.5275 | Train Acc: 74.42%
  1%|▌                                        | 1/80 [02:57<3:53:56, 177.68s/it]Epoch: 02 *****
Train Loss: 0.4003 | Train Acc: 77.90%
  2%|█                                        | 2/80 [05:55<3:51:01, 177.71s/it]Epoch: 03 *****
Train Loss: 0.3713 | Train Acc: 78.74%
  4%|█▌                                       | 3/80 [08:54<

In [9]:
# amnet_train
!python Atom_matching_network/train/amnet_train_fold.py --fold 3

Device: cuda
GPU: NVIDIA GeForce RTX 3050 6GB Laptop GPU
Memory allocated: 0.00 GB
/home/alpiano/miniconda3/envs/chem_env/lib/python3.10/site-packages/torch_geometric/deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
FMNet(
gnn=GIN(111, 512, num_layers=3, batch_norm=False, cat=True, lin=True),

Namespace(num_wl_iterations=3, node_features_dim=111, edge_feature_dim=10, santitize=False, embedding_dim=512, num_layers=3, lr=0.0001, n_epochs=80, batch_size=1, fold=3)
  0%|                                                    | 0/80 [00:00<?, ?it/s]Epoch: 01 *****
Train Loss: 0.5281 | Train Acc: 74.35%
  1%|▌                                        | 1/80 [03:01<3:58:59, 181.51s/it]Epoch: 02 *****
Train Loss: 0.4037 | Train Acc: 77.77%
  2%|█                                        | 2/80 [06:02<3:55:18, 181.01s/it]Epoch: 03 *****
Train Loss: 0.3781 | Train Acc: 78.49%
  4%|█▌                                       | 3/80 [09:04<

In [10]:
# amnet_train
!python Atom_matching_network/train/amnet_train_fold.py --fold 4

Device: cuda
GPU: NVIDIA GeForce RTX 3050 6GB Laptop GPU
Memory allocated: 0.00 GB
/home/alpiano/miniconda3/envs/chem_env/lib/python3.10/site-packages/torch_geometric/deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
FMNet(
gnn=GIN(111, 512, num_layers=3, batch_norm=False, cat=True, lin=True),

Namespace(num_wl_iterations=3, node_features_dim=111, edge_feature_dim=10, santitize=False, embedding_dim=512, num_layers=3, lr=0.0001, n_epochs=80, batch_size=1, fold=4)
  0%|                                                    | 0/80 [00:00<?, ?it/s]Epoch: 01 *****
Train Loss: 0.5269 | Train Acc: 74.45%
  1%|▌                                        | 1/80 [02:54<3:49:46, 174.51s/it]Epoch: 02 *****
Train Loss: 0.4064 | Train Acc: 77.70%
  2%|█                                        | 2/80 [05:50<3:48:10, 175.52s/it]Epoch: 03 *****
Train Loss: 0.3752 | Train Acc: 78.65%
  4%|█▌                                       | 3/80 [08:54<

In [7]:
pip install localmapper

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.7/34.7 MB 14.1 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.5/8.5 MB 23.6 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 25.3 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [19]:
!python Atom_matching_network/Test/test_ensemble.py

/home/alpiano/miniconda3/envs/chem_env/lib/python3.10/site-packages/torch_geometric/typing.py:86: UserWarning: An issue occurred while importing 'torch-scatter'. Disabling its usage. Stacktrace: libcudart.so.11.0: cannot open shared object file: No such file or directory
  warnings.warn(f"An issue occurred while importing 'torch-scatter'. "
/home/alpiano/miniconda3/envs/chem_env/lib/python3.10/site-packages/torch_geometric/typing.py:97: UserWarning: An issue occurred while importing 'torch-cluster'. Disabling its usage. Stacktrace: libcudart.so.11.0: cannot open shared object file: No such file or directory
  warnings.warn(f"An issue occurred while importing 'torch-cluster'. "
/home/alpiano/miniconda3/envs/chem_env/lib/python3.10/site-packages/torch_geometric/typing.py:113: UserWarning: An issue occurred while importing 'torch-spline-conv'. Disabling its usage. Stacktrace: libcudart.so.11.0: cannot open shared object file: No such file or directory
  warnings.warn(
/home/alpiano/minico

In [14]:
# оценка только реакций, где localmapper не уверен, одиночная модель amnet
!python Atom_matching_network/Test/test_batch.py

/home/alpiano/miniconda3/envs/chem_env/lib/python3.10/site-packages/torch_geometric/typing.py:86: UserWarning: An issue occurred while importing 'torch-scatter'. Disabling its usage. Stacktrace: libcudart.so.11.0: cannot open shared object file: No such file or directory
  warnings.warn(f"An issue occurred while importing 'torch-scatter'. "
/home/alpiano/miniconda3/envs/chem_env/lib/python3.10/site-packages/torch_geometric/typing.py:97: UserWarning: An issue occurred while importing 'torch-cluster'. Disabling its usage. Stacktrace: libcudart.so.11.0: cannot open shared object file: No such file or directory
  warnings.warn(f"An issue occurred while importing 'torch-cluster'. "
/home/alpiano/miniconda3/envs/chem_env/lib/python3.10/site-packages/torch_geometric/typing.py:113: UserWarning: An issue occurred while importing 'torch-spline-conv'. Disabling its usage. Stacktrace: libcudart.so.11.0: cannot open shared object file: No such file or directory
  warnings.warn(
/home/alpiano/minico